mybatis:
  typeAliasesPackage: com.viewstar.entity
  mapperLocations: classpath:mapper/*/*.xml
  configLocation: classpath:mybatis-config.xml
environment : dev
server:
  port: 8087
spring:
  application:
    name: userprofilekls
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
logging:
    file: /logs/application-debug.log
    pattern:
        console: "%d %-5level %logger : %msg%n"
        file: "%d %-5level [%thread] %logger : %msg%n"
    level:
        com.viewstar.mapper: DEBUGresultJson=
        org.springframework.web: WARN
        org.apache.spark.deploy.yarn.Client : WARN
        org : WARN